<?php
/*
    pygments.formatters._mapping
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    Formatter mapping defintions. This file is generated by itself. Everytime
    you change something on a builtin formatter defintion, run this script from
    the formatters folder to update it.

    Do not alter the FORMATTERS dictionary by hand.

    :copyright: Copyright 2006-2013 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
*/

# start
$FORMATTERS = [
    'Html' => ['HTML', ['html',], ['*.html', '*.htm'], "Format tokens as HTML 4 ``<span>`` tags within a ``<pre>`` tag, wrapped in a ``<div>`` tag. The ``<div>``'s CSS class can be set by the `cssclass` option."],
    'Html5' => ['HTML5', ['html5',], ['*.html', '*.htm'], "Format tokens as HTML 5."],
    'Null' => ['Text only', ['text', 'null'], ['*.txt',], 'Output the text unchanged without any formatting.'],
    'RawToken' => ['Raw tokens', ['raw', 'tokens'], ['*.raw',], 'Format tokens as a raw representation for storing token streams.'],
];

//@todo: implement auto generator if needed